In [ ]:
import torch
import torch.nn as nn

#class Model(nn.Module):
 # def __init__(self,num_feature):
  #  super(). __init__()
   # self.linear1 = nn.Linear(num_feature, 3)
    #self.ReLu = nn.ReLU()
    #self.linear2 = nn.Linear(3,1)
    #self.sigmoid = nn.Sigmoid()
  #def forward(self,feature):
   # out = self.linear1(feature)
    #out = self.ReLu(out)
    #out = self.linear2(out)
    #out = self.sigmoid(out)
    #return out
class Model(nn.Module):
  def __init__(self,num_feature):
    super().__init__()
    self.net = nn.Sequential(
        nn.Linear(num_feature,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()

    )

  def forward(self,feature):
    out = self.net(feature)
    return out


In [ ]:
#Create dataset
data = torch.rand(100,5)
model = Model(data.shape[1])
model(data)

tensor([[0.3941],
        [0.4071],
        [0.3908],
        [0.4034],
        [0.3902],
        [0.3959],
        [0.3904],
        [0.3893],
        [0.3896],
        [0.3909],
        [0.3909],
        [0.4044],
        [0.3896],
        [0.3896],
        [0.3894],
        [0.3895],
        [0.3909],
        [0.3888],
        [0.3907],
        [0.3891],
        [0.3907],
        [0.3896],
        [0.3902],
        [0.3896],
        [0.4086],
        [0.3908],
        [0.4021],
        [0.3904],
        [0.3911],
        [0.4016],
        [0.3907],
        [0.3906],
        [0.3904],
        [0.3897],
        [0.3904],
        [0.4030],
        [0.3912],
        [0.3905],
        [0.3903],
        [0.3903],
        [0.3888],
        [0.3896],
        [0.3897],
        [0.3903],
        [0.3889],
        [0.3905],
        [0.3887],
        [0.3892],
        [0.3899],
        [0.3900],
        [0.3984],
        [0.3907],
        [0.4091],
        [0.3904],
        [0.3898],
        [0

In [ ]:
model.net[0].weight  # Linear(num_feature, 3) weights


Parameter containing:
tensor([[ 0.3528,  0.1057, -0.0960, -0.1630, -0.0341],
        [ 0.3365, -0.1062, -0.1903, -0.3220,  0.0706],
        [-0.3089,  0.1876, -0.4228, -0.0967,  0.3936]], requires_grad=True)

In [ ]:
#Model.linear1.weight

In [ ]:

model.net[0].bias    # Linear(num_feature, 3) bias

Parameter containing:
tensor([ 0.2607, -0.3247, -0.0270], requires_grad=True)

In [ ]:
model.net[2].weight  # Linear(num_feature, 3) weights


Parameter containing:
tensor([[-0.0242,  0.4067,  0.3453]], requires_grad=True)

In [ ]:

model.net[2].bias    # Linear(num_feature, 3) bias

Parameter containing:
tensor([-0.4386], requires_grad=True)

In [ ]:
#model.linear2.weight

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=data.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [100, 1]                  --
├─Sequential: 1-1                        [100, 1]                  --
│    └─Linear: 2-1                       [100, 3]                  18
│    └─ReLU: 2-2                         [100, 3]                  --
│    └─Linear: 2-3                       [100, 1]                  4
│    └─Sigmoid: 2-4                      [100, 1]                  --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.01